version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - sudo mkdir /opt/gradle
      - wget -c https://services.gradle.org/distributions/gradle-4.2.1-bin.zip
      - sudo unzip -d /opt/gradle gradle-4.2.1-bin.zip
      - export PATH=$PATH:/opt/gradle/gradle-4.2.1/bin
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - build/libs/*.jar
    - scripts/*.sh
    - appspec.yml
  #com/mycompany/app/HelloWorld.java, specifying yes will place this file in /HelloWorld.java
  discard-paths: yes
